daysUntilStale: 14
daysUntilClose: 28
exemptLabels:
  - pinned
  - security
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
    any recent activity. It will be closed in fourteen (14) days if no further
    activity occurs. Thanks for your contributions.
closeComment: true
